### ISSUE TITLE
Feature request: support multiple Redmine instances

### ISSUE THREAD

**Issue by vividtone** [emsk/redmine-notifier#3]
I think it would be great if remdine-notifier supports multiple Redmine instances. It supports only 1 Redmine URL for now, but I usually work with three or four Redmine instances. So I cannot make use of redmine-notifier for my work. I feel very sorry about that.

Thank you for making such a cool software.

**Comment by emsk** [comment]
@vividtone Thank you for your suggestion.
Redmine Notifier has supported multiple Redmine URLs since **v0.7.1**.

Would you check the version of Redmine Notifier you are using?

The settings window of v0.7.1 has three buttons in the bottom right.
https://raw.githubusercontent.com/emsk/redmine-notifier/master/examples/redmine_notifier_settings.png

**Comment by vividtone** [comment]
>  Redmine Notifier has supported multiple Redmine URLs since v0.7.1.

Thank you for the help and sorry for bothering.

I updated the app and now I can see the updates of multiple Redmine instances.
Thanks again, for making the great software.
